name: Test Package

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install package in development mode
      run: |
        pip install -e .
        
    - name: Test basic import
      run: |
        python -c "from jobspy_enhanced import scrape_jobs; print('Import successful')"
        
    - name: Test scraper imports
      run: |
        python -c "
        from jobspy_enhanced.linkedin import LinkedIn
        from jobspy_enhanced.indeed import Indeed
        from jobspy_enhanced.glassdoor import Glassdoor
        from jobspy_enhanced.ziprecruiter import ZipRecruiter
        from jobspy_enhanced.google import Google
        from jobspy_enhanced.naukri import Naukri
        print('All scraper imports successful')
        "
        
    - name: Test model imports
      run: |
        python -c "
        from jobspy_enhanced.model import JobType, Location, JobResponse, Country, Site
        print('All model imports successful')
        "
